# Generated by Django 4.2.3 on 2023-11-06 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRESENT", "선물 펀딩"),
                            ("SOSO", "소소 펀딩"),
                            ("DREAM", "드림 펀딩"),
                        ],
                        default="PRESENT",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("product", models.CharField(max_length=50)),
                ("total_price", models.IntegerField()),
                ("accumulation", models.IntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("content", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("funding_image", models.ImageField(upload_to="fundings/")),
                ("qr_image", models.ImageField(blank=True, null=True, upload_to="qr/")),
                ("likes_cnt", models.IntegerField(default=0)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "funding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.fundings"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
