# Generated by Django 4.2.3 on 2023-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundings",
            name="account_num",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="fundings",
            name="delievery",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="fundings",
            name="type",
            field=models.CharField(
                choices=[("선물 펀딩", "선물 펀딩"), ("소소 펀딩", "소소 펀딩"), ("드림 펀딩", "드림 펀딩")],
                default="선물 펀딩",
                max_length=10,
            ),
        ),
    ]
