# Generated by Django 4.2.3 on 2023-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_fundings_account_num_fundings_delievery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundings",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
